#ifndef _BLOCKDATABASE_H
#define _BLOCKDATABASE_H

#include <array>
#include <string>

#include <glm/glm.hpp>

const int STONE = 0;
const int ANDESITE = 1;
const int DIRT = 2;

const int GRASS_SIDE = 3;
const int GRASS_TOP = 4;

const int SNOW_SIDE = 5;

const int PODZIL_TOP = 6;
const int PODZIL_SIDE = 7;

const int OAK_PLANK = 8;
const int SPRUCE_PLANK = 9;
const int BIRCH_PLANK = 10;
const int JUNGLE_PLANK = 11;
const int ACACIA_PLANK = 12;
const int DARK_OAK_PLANK = 13;

const int OAK_SAPPLING = 14;
const int SPRUCE_SAPPLING = 15;
const int BIRCH_SAPPLING = 16;
const int JUNGLE_SAPPLING = 17;
const int ACACIA_SAPPLING = 18;
const int DARK_OAK_SAPPLING = 19;

const int OAK_LOG_TOP = 20;
const int OAK_LOG_SIDE = 21;

const int SPRUCE_LOG_TOP = 22;
const int SPRUCE_LOG_SIDE = 23;

const int BIRCH_LOG_TOP = 24;
const int BIRCH_LOG_SIDE = 25;

const int JUNGLE_LOG_TOP = 26;
const int JUNGLE_LOG_SIDE = 27;

const int ACACIA_LOG_TOP = 28;
const int ACACIA_LOG_SIDE = 29;

const int DARK_OAK_LOG_TOP = 30;
const int DARK_OAK_LOG_SIDE = 31;

const int COBBLESTONE = 32;
const int MOSSY_COBBLESTONE = 33;

const int SAND = 34;
const int RED_SAND = 35;
const int GRAVEL = 36;

const int COAL_ORE = 37;
const int IRON_ORE = 38;
const int LAPIS_ORE = 39;
const int EMERALD_ORE = 40;
const int GOLD_ORE = 41;
const int REDSTONE_ORE = 42;
const int DIAMOND_ORE = 43;
const int QUARTZ_ORE = 44;

const int COAL_BLOCK = 45;
const int IRON_BLOCK = 46;
const int LAPIS_BLOCK = 47;
const int EMERALD_BLOCK = 48;
const int GOLD_BLOCK = 49;
const int REDSTONE_BLOCK = 50;
const int DIAMOND_BLOCK = 51;

const int OAK_LEAVES_SIDE = 52;
const int OAK_LEAVES_TOP = 53;
const int SPRUCE_LEAVES_SIDE = 54;
const int SPRUCE_LEAVES_TOP = 55;
const int BIRCH_LEAVES_SIDE = 56;
const int BIRCH_LEAVES_TOP = 57;
const int JUNGLE_LEAVES_SIDE = 58;
const int JUNGLE_LEAVES_TOP = 59;
const int ACACIA_LEAVES_SIDE = 60;
const int ACACIA_LEAVES_TOP = 61;
const int DARK_OAK_LEAVES_SIDE = 62;
const int DARK_OAK_LEAVES_TOP = 63;

const int BEDROCK = 64;
const int OBSIDIAN = 65;

const int STONE_BRICK = 70;
const int MOSSY_STONE_BRICK = 71;
const int CRACKED_STONE_BRICK = 72;
const int CHISELED_STONE_BRICK = 73;

const int CRAFTING_TABLE_TOP = 160;
const int CRAFTING_TABLE_FACE = 161;
const int CRAFTING_TABLE_SIDE = 162;

const int FURNACE_TOP = 163;
const int FURNACE_SIDE = 164;
const int FURNACE_FACE = 165;

struct TextureInfo
{
  int face;
  int side;
  int top;
  int bottom;
};

const TextureInfo STONE_TEXTURE = {STONE, STONE, STONE, STONE};
const TextureInfo ANDESITE_TEXTURE = {ANDESITE, ANDESITE, ANDESITE, ANDESITE};
const TextureInfo DIRT_TEXTURE = {DIRT, DIRT, DIRT, DIRT};

const TextureInfo GRASS_TEXTURE = {GRASS_SIDE, GRASS_SIDE, GRASS_TOP, DIRT};
const TextureInfo SNOW_TEXTURE = {SNOW_SIDE, SNOW_SIDE, SNOW_SIDE, DIRT};
const TextureInfo PODZIL_TEXTURE = {PODZIL_SIDE, PODZIL_SIDE, PODZIL_TOP, DIRT};

const TextureInfo OAK_PLANK_TEXTURE = {OAK_PLANK, OAK_PLANK, OAK_PLANK, OAK_PLANK};
const TextureInfo SPRUCE_PLANK_TEXTURE = {SPRUCE_PLANK, SPRUCE_PLANK, SPRUCE_PLANK, SPRUCE_PLANK};
const TextureInfo BIRCH_PLANK_TEXTURE = {BIRCH_PLANK, BIRCH_PLANK, BIRCH_PLANK, BIRCH_PLANK};
const TextureInfo JUNGLE_PLANK_TEXTURE = {JUNGLE_PLANK, JUNGLE_PLANK, JUNGLE_PLANK, JUNGLE_PLANK};
const TextureInfo ACACIA_PLANK_TEXTURE = {ACACIA_PLANK, ACACIA_PLANK, ACACIA_PLANK, ACACIA_PLANK};
const TextureInfo DARK_OAK_PLANK_TEXTURE = {DARK_OAK_PLANK, DARK_OAK_PLANK, DARK_OAK_PLANK, DARK_OAK_PLANK};

const TextureInfo OAK_LOG_TEXTURE = {OAK_LOG_SIDE, OAK_LOG_SIDE, OAK_LOG_TOP, OAK_LOG_TOP};
const TextureInfo SPRUCE_LOG_TEXTURE = {SPRUCE_LOG_SIDE, SPRUCE_LOG_SIDE, SPRUCE_LOG_TOP, SPRUCE_LOG_TOP};
const TextureInfo BIRCH_LOG_TEXTURE = {BIRCH_LOG_SIDE, BIRCH_LOG_SIDE, BIRCH_LOG_TOP, BIRCH_LOG_TOP};
const TextureInfo JUNGLE_LOG_TEXTURE = {JUNGLE_LOG_SIDE, JUNGLE_LOG_SIDE, JUNGLE_LOG_TOP, JUNGLE_LOG_TOP};
const TextureInfo ACACIA_LOG_TEXTURE = {ACACIA_LOG_SIDE, ACACIA_LOG_SIDE, ACACIA_LOG_TOP, ACACIA_LOG_TOP};
const TextureInfo DARK_OAK_LOG_TEXTURE = {DARK_OAK_LOG_SIDE, DARK_OAK_LOG_SIDE, DARK_OAK_LOG_TOP, DARK_OAK_LOG_TOP};

const TextureInfo COBBLESTONE_TEXTURE = {COBBLESTONE, COBBLESTONE, COBBLESTONE, COBBLESTONE};
const TextureInfo MOSSY_COBBLESTONE_TEXUTRE = {MOSSY_COBBLESTONE, MOSSY_COBBLESTONE, MOSSY_COBBLESTONE, MOSSY_COBBLESTONE};

const TextureInfo SAND_TEXTURE = {SAND, SAND, SAND, SAND};
const TextureInfo RED_SAND_TEXTURE = {RED_SAND, RED_SAND, RED_SAND, RED_SAND};
const TextureInfo GRAVEL_TEXTURE = {GRAVEL, GRAVEL, GRAVEL, GRAVEL};

const TextureInfo COAL_ORE_TEXTURE = {COAL_ORE, COAL_ORE, COAL_ORE, COAL_ORE};
const TextureInfo IRON_ORE_TEXTURE = {IRON_ORE, IRON_ORE, IRON_ORE, IRON_ORE};
const TextureInfo LAPIS_ORE_TEXTURE = {LAPIS_ORE, LAPIS_ORE, LAPIS_ORE, LAPIS_ORE};
const TextureInfo EMERALD_ORE_TEXTURE = {EMERALD_ORE, EMERALD_ORE, EMERALD_ORE, EMERALD_ORE};
const TextureInfo GOLD_ORE_TEXTURE = {GOLD_ORE, GOLD_ORE, GOLD_ORE, GOLD_ORE};
const TextureInfo REDSTONE_ORE_TEXTURE = {REDSTONE_ORE, REDSTONE_ORE, REDSTONE_ORE, REDSTONE_ORE};
const TextureInfo DIAMOND_ORE_TEXTURE = {DIAMOND_ORE, DIAMOND_ORE, DIAMOND_ORE, DIAMOND_ORE};
const TextureInfo QUARTZ_ORE_TEXTURE = {QUARTZ_ORE, QUARTZ_ORE, QUARTZ_ORE, QUARTZ_ORE};

const TextureInfo COAL_BLOCK_TEXTURE = {COAL_BLOCK, COAL_BLOCK, COAL_BLOCK, COAL_BLOCK};
const TextureInfo IRON_BLOCK_TEXTURE = {IRON_BLOCK, IRON_BLOCK, IRON_BLOCK, IRON_BLOCK};
const TextureInfo LAPIS_BLOCK_TEXTURE = {LAPIS_BLOCK, LAPIS_BLOCK, LAPIS_BLOCK, LAPIS_BLOCK};
const TextureInfo EMERALD_BLOCK_TEXTURE = {EMERALD_BLOCK, EMERALD_BLOCK, EMERALD_BLOCK, EMERALD_BLOCK};
const TextureInfo GOLD_BLOCK_TEXTURE = {GOLD_BLOCK, GOLD_BLOCK, GOLD_BLOCK, GOLD_BLOCK};
const TextureInfo REDSTONE_BLOCK_TEXTURE = {REDSTONE_BLOCK, REDSTONE_BLOCK, REDSTONE_BLOCK, REDSTONE_BLOCK};
const TextureInfo DIAMOND_BLOCK_TEXTURE = {DIAMOND_BLOCK, DIAMOND_BLOCK, DIAMOND_BLOCK, DIAMOND_BLOCK};

const TextureInfo OAK_LEAVES_TEXTURE = {OAK_LEAVES_SIDE, OAK_LEAVES_SIDE, OAK_LEAVES_SIDE, OAK_LEAVES_SIDE};
const TextureInfo SPRUCE_LEAVES_TEXTURE = {SPRUCE_LEAVES_SIDE, SPRUCE_LEAVES_SIDE, SPRUCE_LEAVES_SIDE, SPRUCE_LEAVES_SIDE};
const TextureInfo BIRCH_LEAVES_TEXTURE = {BIRCH_LEAVES_SIDE, BIRCH_LEAVES_SIDE, BIRCH_LEAVES_SIDE, BIRCH_LEAVES_SIDE};
const TextureInfo JUNGLE_LEAVES_TEXTURE = {JUNGLE_LEAVES_SIDE, JUNGLE_LEAVES_SIDE, JUNGLE_LEAVES_SIDE, JUNGLE_LEAVES_SIDE};
const TextureInfo ACACIA_LEAVES_TEXTURE = {ACACIA_LEAVES_SIDE, ACACIA_LEAVES_SIDE, ACACIA_LEAVES_SIDE, ACACIA_LEAVES_SIDE};
const TextureInfo DARK_OAK_LEAVES_TEXTURE = {DARK_OAK_LEAVES_SIDE, DARK_OAK_LEAVES_SIDE, DARK_OAK_LEAVES_SIDE, DARK_OAK_LEAVES_SIDE};

const TextureInfo BEDROCK_TEXTURE = {BEDROCK, BEDROCK, BEDROCK, BEDROCK};
const TextureInfo OBSIDIAN_TEXTURE = {OBSIDIAN, OBSIDIAN, OBSIDIAN, OBSIDIAN};

const TextureInfo STONE_BRICK_TEXTURE = {STONE_BRICK, STONE_BRICK, STONE_BRICK, STONE_BRICK};
const TextureInfo MOSSY_STONE_BRICK_TEXTURE = {MOSSY_STONE_BRICK, MOSSY_STONE_BRICK, MOSSY_STONE_BRICK, MOSSY_STONE_BRICK};
const TextureInfo CRACKED_STONE_BRICK_TEXTURE = {CRACKED_STONE_BRICK, CRACKED_STONE_BRICK, CRACKED_STONE_BRICK, CRACKED_STONE_BRICK};
const TextureInfo CHISELED_STONE_BRICK_TEXTURE = {CHISELED_STONE_BRICK, CHISELED_STONE_BRICK, CHISELED_STONE_BRICK, CHISELED_STONE_BRICK};

const TextureInfo CRAFTING_TABLE_TEXTURE = {CRAFTING_TABLE_FACE, CRAFTING_TABLE_SIDE, CRAFTING_TABLE_TOP, OAK_PLANK};
const TextureInfo FURNACE_TEXTURE = {FURNACE_FACE, FURNACE_SIDE, FURNACE_TOP, FURNACE_TOP};

struct BlockBaseInformation
{
  std::string blockId;
  TextureInfo textureReference;
};

struct BlockInformation
{
  std::string blockId;
  TextureInfo textureReference;
  std::array<glm::vec2, 36> textureCoordinates;
};

const int BLOCK_COUNT = 52;

const BlockBaseInformation BLOCK_ATLAS[BLOCK_COUNT] = {
    {"stone", STONE_TEXTURE},
    {"andesite", ANDESITE_TEXTURE},
    {"dirt", DIRT_TEXTURE},
    {"grass", GRASS_TEXTURE},
    {"snow", SNOW_TEXTURE},
    {"podzil", PODZIL_TEXTURE},
    {"oak_plank", OAK_PLANK_TEXTURE},
    {"spruce_plank", SPRUCE_PLANK_TEXTURE},
    {"birch_plank", BIRCH_PLANK_TEXTURE},
    {"jungle_plank", JUNGLE_PLANK_TEXTURE},
    {"acacia_plank", ACACIA_PLANK_TEXTURE},
    {"dark_oak_plank", DARK_OAK_PLANK_TEXTURE},
    {"oak_log", OAK_LOG_TEXTURE},
    {"spruce_log", SPRUCE_LOG_TEXTURE},
    {"birch_log", BIRCH_LOG_TEXTURE},
    {"jungle_log", JUNGLE_LOG_TEXTURE},
    {"acacia_log", ACACIA_LOG_TEXTURE},
    {"dark_oak_log", DARK_OAK_LOG_TEXTURE},
    {"cobblestone", COBBLESTONE_TEXTURE},
    {"mossy_cobblestone", MOSSY_COBBLESTONE_TEXUTRE},
    {"sand", SAND_TEXTURE},
    {"red_sand", RED_SAND_TEXTURE},
    {"gravel", GRAVEL_TEXTURE},
    {"coal_ore", COAL_ORE_TEXTURE},
    {"iron_ore", IRON_ORE_TEXTURE},
    {"lapis_ore", LAPIS_ORE_TEXTURE},
    {"emerald_ore", EMERALD_ORE_TEXTURE},
    {"gold_ore", GOLD_ORE_TEXTURE},
    {"redstone_ore", REDSTONE_ORE_TEXTURE},
    {"diamond_ore", DIAMOND_ORE_TEXTURE},
    {"quartz_ore", QUARTZ_ORE_TEXTURE},
    {"coal_block", COAL_BLOCK_TEXTURE},
    {"iron_block", IRON_BLOCK_TEXTURE},
    {"lapis_block", LAPIS_BLOCK_TEXTURE},
    {"emerald_block", EMERALD_BLOCK_TEXTURE},
    {"gold_block", GOLD_BLOCK_TEXTURE},
    {"redstone_block", REDSTONE_BLOCK_TEXTURE},
    {"diamond_block", DIAMOND_BLOCK_TEXTURE},
    {"oak_leaves", OAK_LEAVES_TEXTURE},
    {"spruce_leaves", SPRUCE_LEAVES_TEXTURE},
    {"birch_leaves", BIRCH_LEAVES_TEXTURE},
    {"jungle_leaves", JUNGLE_LEAVES_TEXTURE},
    {"acacia_leaves", ACACIA_LEAVES_TEXTURE},
    {"dark_oak_leaves", DARK_OAK_LEAVES_TEXTURE},
    {"bedrock", BEDROCK_TEXTURE},
    {"obsidian", OBSIDIAN_TEXTURE},
    {"stone_brick", STONE_BRICK_TEXTURE},
    {"mossy_stone_brick", MOSSY_STONE_BRICK_TEXTURE},
    {"cracked_stone_brick", CRACKED_STONE_BRICK_TEXTURE},
    {"chiseled_stone_brick", CHISELED_STONE_BRICK_TEXTURE},
    {"crafting_table", CRAFTING_TABLE_TEXTURE},
    {"furnace", FURNACE_TEXTURE},
};

class BlockDatabase
{
private:
  BlockDatabase() {}

  static const int HORIZONTAL_TEXTURE_COUNT = 32;
  static const int VERTICAL_TEXTURE_COUNT = 11;

  static BlockInformation blockInformation[BLOCK_COUNT];

public:
  static void Initialize();

  static BlockInformation GetBlockInformation(std::string blockId);
  static BlockInformation GetBlockInformationIndex(int index);
};

#endif